# Generated by Django 5.1.6 on 2025-12-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='inside',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiview.smallestdata'),
        ),
    ]
